openapi: '3.0.2'
info:
  title: PiEar REST API
  version: '1.0'
servers:
  - url: localhost:9090
paths:
  /channel-name/{id}/{name}:
    description: Get and set a channel name
    parameters: 
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: ID of the channel to get the name of
    get:
      description: 'Get the channel name'
      responses:
        '200':
          description: OK
    put:
      description: 'Set the channel name'
      responses:
        '200':
          description: OK
      parameters: 
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: new name of the channel
  /bpm/{bpm}:
    description: Get and set the bpm
    get:
      description: 'Get the current BPM'
      responses:
        '200':
          description: OK
    put:
      description: 'Set the current BPM'
      responses:
        '200':
          description: OK
      parameters: 
        - in: path
          name: bpm
          schema:
            type: integer
          required: true
          description: new bpm
