openapi: '3.0.2'
info:
  title: PiEar REST API
  version: '1.0'
servers:
  - url: localhost
paths:
  /channel/<id>:
    get:
      responses:
        '200':
          description: "text: <channel_name>"
    post:
      responses:
        '200':
          description: "body: <channel_name>"
